import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import rateLimit from "express-rate-limit";
import dotenv from "dotenv";
import {dbHealth} from "./db.js";
import {parse,nearbySchema,journeySchema,trainNumber} from "./validate.js";
import {nearbyStations,nearbyCrossings,crossingsNearRoute,importOsmAround} from "./railway.js";
import {route} from "./geospatial.js";
import {trainStatus,liveTrains} from "./train.js";
import {prakasamHealth,prakasamLiveTrains,prakasamTrainStatus,prakasamGate,prakasamRailRun} from "./prakasam.js";
dotenv.config();
const app=express(); app.disable("x-powered-by"); app.use(helmet());
app.use(cors({origin:process.env.CORS_ORIGIN?.split(",").map(x=>x.trim())||"*"}));
app.use(express.json({limit:"100kb"})); app.use(morgan("combined"));
app.use(rateLimit({windowMs:60000,limit:120,standardHeaders:"draft-8",legacyHeaders:false}));
const ok=(data,extra={})=>({success:true,...extra,data});
const fail=(e,res)=>res.status(e.status||500).json({success:false,error:{code:e.code||"INTERNAL_ERROR",message:e.status?e.message:"Request failed"}});
app.get("/health",async(_,res)=>{try{const dbOk=await dbHealth();res.json({status:"ok",database:dbOk?"connected":"unavailable",prakasam_trial:prakasamHealth(),cache:"not_configured",train_api:process.env.TRAIN_API_BASE_URL?"configured":"unavailable",timestamp:new Date().toISOString()});}catch(e){res.status(503).json({status:"degraded",database:"unavailable",prakasam_trial:prakasamHealth(),cache:"not_configured",train_api:process.env.TRAIN_API_BASE_URL?"configured":"unavailable",timestamp:new Date().toISOString()});}});
app.get("/api/stations/nearby",async(req,res)=>{try{const p=parse(nearbySchema,req.query);res.json(ok(await nearbyStations(p.latitude,p.longitude,p.radius),{data_status:"MAPPED"}));}catch(e){fail(e,res);}});
app.get("/api/crossings/nearby",async(req,res)=>{try{const p=parse(nearbySchema,req.query);res.json(ok(await nearbyCrossings(p.latitude,p.longitude,p.radius),{data_status:"MAPPED"}));}catch(e){fail(e,res);}});
app.get("/api/trains/:trainNumber/status",async(req,res)=>{try{const n=parse(trainNumber,req.params.trainNumber);const trial=prakasamTrainStatus(n);res.json(ok(trial.train?trial:await trainStatus(n),{data_status:trial.train?"SIMULATED_TRIAL":"LIVE"}));}catch(e){fail(e,res);}});
app.get("/api/trains/live",async(_,res)=>{const trial=prakasamLiveTrains();res.json(ok(trial.trains.length?trial:await liveTrains(),{data_status:trial.trains.length?"SIMULATED_TRIAL":"LIVE"}));});
app.get("/api/prakasam/health",(_,res)=>res.json(ok(prakasamHealth())));
app.get("/api/prakasam/trains/live",(_,res)=>res.json(ok(prakasamLiveTrains(),{data_status:"SIMULATED_TRIAL"})));
app.get("/api/prakasam/trains/:trainNumber/status",async(req,res)=>{try{const n=parse(trainNumber,req.params.trainNumber);res.json(ok(prakasamTrainStatus(n),{data_status:"SIMULATED_TRIAL"}));}catch(e){fail(e,res);}});
app.get("/api/prakasam/gates/:gateCode",async(req,res)=>{const d=prakasamGate(req.params.gateCode);if(!d)return res.status(404).json({success:false,error:{code:"GATE_NOT_FOUND",message:"Prakasam gate not found"}});res.json(ok(d,{data_status:"SIMULATED_TRIAL"}));});
app.post("/api/prakasam/rail-run",async(req,res)=>{try{const p=parse(journeySchema,req.body);const r=await route(p.start,p.destination);const railRun=prakasamRailRun({user:p.start,routeGeometry:r.geometry});res.json(ok({route:r,...railRun},{data_status:"SIMULATED_TRIAL"}));}catch(e){fail(e,res);}});
app.get("/api/trains/search",async(req,res)=>res.json(ok({query:req.query.q||"",trains:[],live:false,status:"unavailable",reason:"Configure a verified train API adapter"})));
app.post("/api/route",async(req,res)=>{try{const p=parse(journeySchema,req.body);res.json(ok(await route(p.start,p.destination)));}catch(e){fail(e,res);}});
app.post("/api/journey/overview",async(req,res)=>{try{const p=parse(journeySchema,req.body);const r=await route(p.start,p.destination);const [stations,crossings]=await Promise.all([nearbyStations(p.start.latitude,p.start.longitude,25000),crossingsNearRoute(r.geometry,250)]);res.json(ok({start:p.start,destination:p.destination,route:r,crossings,stations,trains:prakasamLiveTrains().trains,data_status:{map:"available",stations:"available",crossings:"available",live_train:"SIMULATED_TRIAL",live_gate:"SIMULATED_TRIAL"}}));}catch(e){fail(e,res);}});
app.get("/api/osm/import-preview",async(req,res)=>{try{const p=parse(nearbySchema,req.query);const d=await importOsmAround(p.latitude,p.longitude,p.radius,process.env.OVERPASS_URL||"https://overpass-api.de/api/interpreter");res.json(ok(d,{data_status:"MAPPED"}));}catch(e){fail(e,res);}});
app.use((_,res)=>res.status(404).json({success:false,error:{code:"NOT_FOUND",message:"Endpoint not found"}}));
app.use((err,_,res)=>{console.error(err);res.status(500).json({success:false,error:{code:"INTERNAL_ERROR",message:"Request failed"}})});
const port=Number(process.env.PORT||8080);app.listen(port,()=>console.log(`RAILCUE backend listening on :${port}`));export default app;
